# placeholder values for prototyping
---
Strap:
  bearing:
  # Sum up value over all railcars
    force: 17792.888000000003
  rolling:
  # Calculate weighted average of ratio times mass static for each railcar divided by total mass static
    ratio: 0.000750000082673352
  davis_b:
  # Calculate weighted average of davis_b times mass static for each railcar divided by total mass static
    davis_b: 0.00003355404807951647
  aerodynamic:
  # Equal to 0.5*Cd*A, sum up value over all railcars
    drag_area: 8.440293051104742
  grade:
    idx_front: 0
    idx_back: 0
