[book]
authors = ["Chad Baker"]
language = "en"
multilingual = false
src = "src"
title = "ALTRIOS Documentation"

[output.html.fold]
enable = true
level = 0

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]